package io.vlingo.xoom.auth.infrastructure;

public enum Events {
  RolePermissionAttached,
  UserUnassignedFromRole,
  UserRegistered,
  TenantDeactivated,
  PermissionProvisioned,
  TenantDescriptionChanged,
  UserAssignedToRole,
  UserAssignedToGroup,
  UserCredentialRemoved,
  PermissionConstraintEnforced,
  GroupAssignedToGroup,
  UserCredentialReplaced,
  TenantNameChanged,
  GroupAssignedToRole,
  GroupDescriptionChanged,
  GroupUnassignedFromRole,
  GroupUnassignedFromGroup,
  RoleProvisioned,
  UserUnassignedFromGroup,
  GroupProvisioned,
  TenantActivated,
  PermissionConstraintForgotten,
  UserCredentialAdded,
  UserProfileReplaced,
  PermissionDescriptionChanged,
  UserDeactivated,
  RoleDescriptionChanged,
  TenantSubscribed,
  UserActivated,
  RolePermissionDetached,
  PermissionConstraintReplacementEnforced,
}
