name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '15 3 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Deploy
    uses: vlingo/xoom-platform/.github/workflows/build.yml@master
    secrets: inherit
